"""User schemas.

Pydantic models for the users feature. These models define the HTTP
contract that the mobile client codes against. Every field is
explicitly typed and documented so the OpenAPI spec generated by
FastAPI is complete.

Naming convention:
    *Request  — validated on incoming HTTP calls.
    *Response — serialized on outgoing HTTP responses.
"""

import re
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.core.constants import (
    Country,
    Currency,
    PIN_LENGTH,
    TAG_ALLOWED_PATTERN,
    TAG_MAX_LENGTH,
    TAG_MIN_LENGTH,
)


# ---------------------------------------------------------------------------
# Requests
# ---------------------------------------------------------------------------

class UserCreateRequest(BaseModel):
    """Payload sent by the client immediately after Firebase sign-up.

    All name fields are required — KYC verification later matches them
    against the government ID, so partial names will fail verification.
    """

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    first_name: str = Field(
        ...,
        min_length=1,
        max_length=80,
        description="Given name as it appears on the user's government ID.",
        examples=["David"],
    )
    middle_name: str = Field(
        ...,
        min_length=1,
        max_length=80,
        description="Middle name as it appears on the user's government ID.",
        examples=["Chukwuemeka"],
    )
    last_name: str = Field(
        ...,
        min_length=1,
        max_length=80,
        description="Family name as it appears on the user's government ID.",
        examples=["Okafor"],
    )
    country: Country = Field(
        ...,
        description="Two-letter ISO country code where the user resides.",
        examples=["NG"],
    )
    phone: str = Field(
        ...,
        min_length=7,
        max_length=20,
        description="Phone number in E.164 format.",
        examples=["+2348012345678"],
    )

    @field_validator("first_name", "middle_name", "last_name")
    @classmethod
    def _validate_name(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("Name fields cannot be blank.")
        if any(ch.isdigit() for ch in value):
            raise ValueError("Name fields cannot contain digits.")
        return value

    @field_validator("phone")
    @classmethod
    def _validate_phone(cls, value: str) -> str:
        if not value.startswith("+"):
            raise ValueError("Phone number must be in E.164 format (start with '+').")
        if not value[1:].isdigit():
            raise ValueError("Phone number must contain only digits after '+'.")
        return value


class TagClaimRequest(BaseModel):
    """Payload for claiming a @tag."""

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    tag: str = Field(
        ...,
        min_length=TAG_MIN_LENGTH,
        max_length=TAG_MAX_LENGTH,
        description="Desired @tag without the leading '@'.",
        examples=["temi"],
    )

    @field_validator("tag")
    @classmethod
    def _validate_tag(cls, value: str) -> str:
        normalized = value.lower().lstrip("@")
        if not re.fullmatch(TAG_ALLOWED_PATTERN, normalized):
            raise ValueError(
                "Tag may only contain lowercase letters, numbers, and underscores."
            )
        return normalized


class SetPinRequest(BaseModel):
    """Payload for setting the user's PIN."""

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    pin: str = Field(
        ...,
        min_length=PIN_LENGTH,
        max_length=PIN_LENGTH,
        description=f"{PIN_LENGTH}-digit PIN.",
        examples=["48392"],
    )

    @field_validator("pin")
    @classmethod
    def _validate_pin(cls, value: str) -> str:
        if not value.isdigit():
            raise ValueError("PIN must contain only digits.")
        if len(set(value)) == 1:
            raise ValueError("PIN cannot be a single repeated digit.")
        return value


class VerifyPinRequest(BaseModel):
    """Payload for verifying the user's PIN."""

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    pin: str = Field(
        ...,
        min_length=PIN_LENGTH,
        max_length=PIN_LENGTH,
        description=f"{PIN_LENGTH}-digit PIN.",
        examples=["48392"],
    )

    @field_validator("pin")
    @classmethod
    def _validate_pin(cls, value: str) -> str:
        if not value.isdigit():
            raise ValueError("PIN must contain only digits.")
        return value


class VerifyPhoneRequest(BaseModel):
    """Payload for marking the user's phone as verified."""

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    phone_number: str = Field(
        ...,
        min_length=7,
        max_length=20,
        description="Phone number in E.164 format returned by Firebase.",
        examples=["+2348012345678"],
    )

    @field_validator("phone_number")
    @classmethod
    def _validate_phone(cls, value: str) -> str:
        if not value.startswith("+"):
            raise ValueError("Phone number must be in E.164 format (start with '+').")
        if not value[1:].isdigit():
            raise ValueError("Phone number must contain only digits after '+'.")
        return value


# ---------------------------------------------------------------------------
# Responses
# ---------------------------------------------------------------------------

class UserResponse(BaseModel):
    """Public user profile returned by the API."""

    model_config = ConfigDict(from_attributes=True)

    uid: str = Field(..., description="Firebase uid.")
    first_name: str = Field(..., description="Given name.")
    middle_name: str = Field(..., description="Middle name.")
    last_name: str = Field(..., description="Family name.")
    tag: str | None = Field(
        None,
        description="The user's @tag (without the leading '@'), or null if unclaimed.",
    )
    country: Country = Field(..., description="Two-letter ISO country code.")
    currency: Currency = Field(..., description="Default settlement currency.")
    phone: str = Field(..., description="Phone number in E.164 format.")
    email: str | None = Field(None, description="Email address, if available.")
    email_verified: bool = Field(
        False,
        description="True once the email verification OTP has been confirmed.",
    )
    phone_verified: bool = Field(
        False,
        description="True once the phone has been confirmed via SMS.",
    )
    identity_verified: bool = Field(
        False,
        description="True once BVN/national ID and face verification pass.",
    )
    account_number: str = Field(
        ...,
        description="NovaBanq account number for inbound bank transfers.",
        examples=["NB0147293810"],
    )
    pin_set: bool = Field(
        False,
        description="True once the user has set a transaction PIN.",
    )
    avatar_url: str | None = Field(
        None,
        description="Optional URL of the user's profile picture.",
    )
    created_at: datetime = Field(..., description="Account creation timestamp (UTC).")


class PinVerifyResponse(BaseModel):
    """Returned after a successful PIN verification."""

    model_config = ConfigDict(frozen=True)

    verified: bool = Field(..., description="Always true on a 200 response.")


class PhoneVerifyResponse(BaseModel):
    """Returned after a phone has been successfully verified."""

    model_config = ConfigDict(frozen=True)

    verified: bool = Field(..., description="Always true on a 200 response.")
    phone_number: str = Field(
        ...,
        description="The phone number that was confirmed.",
        examples=["+2348012345678"],
    )


class PinResetResponse(BaseModel):
    """Returned after a successful PIN reset."""

    model_config = ConfigDict(frozen=True)

    reset: bool = Field(..., description="Always true on a 200 response.")
    message: str = Field(
        default="PIN cleared. You may now set a new PIN.",
        description="Human-readable confirmation for the client.",
    )